name: .NET Core

on:
  pull_request:
    branches: 
      - develop

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build with dotnet
      run: dotnet build ./backend/backend.sln --configuration Release
    - name: Test with dotnet
      run: dotnet test ./backend/backend.sln --configuration Release
